version: '3'
services:
  phone_front:
    image: upachko/phone_front:latest
    container_name: phone_front
    ports:
      - "5173:80"
    depends_on:
      - phone_api
  phone_api:
    image: upachko/phone_api:latest
    container_name: phone_api
    ports:
      - "3000:3000"
      - "9000:9000"
    environment:
#     main
      PORT: 3000
      PRODUCTION: true
      SENTRY_KEY:
#     rabbit
      RABBIT_USER: root
      RABBIT_PASSWORD: root
      RABBIT_HOST: phone_rabbit:5672
#     redis
      REDIS_HOST: phone_redis
      REDIS_PORT: 6379
#     db
      DB_HOST: phone_mariadb
      DB_PORT: 3306
      DB_USER: user1
      DB_PASSWORD: user1
      DB_NAME: db_parser
#     rucaptcha
      RUCAPTCHA_API:
#     wss
      WS_HOST: http://localhost
      WS_PORT: 9000
#     timeouts.  раз в сколько времени что-то. в секундах
      #запускается парсер на оплату телефонов. 2 мин
      TIMEOUT_PAY: 120
      #запускается парсер на сбор данных по телефонам. 2 мин
      TIMEOUT_PARSE: 120
      #запускается парсер на сброс статуса парсинга. 3 мин
      TIMEOUT_RESET_PARSE: 180
      #запускается парсер на сброс статуса оплаты. 3 мин
      TIMEOUT_RESET_PAY: 180
      #обновляются данные по телефонам раз в 2ч
      PERIOD_PARSE: 7200
      #сбрасываются статусы оплаты если оплаты не было 4ч
      PERIOD_RESET_PAY: 14400
      #сбрасываются статусы парсинга если парсинга не было 4ч
      PERIOD_RESET_PARSE: 14400
    depends_on:
      - phone_mariadb
      - phone_rabbit
      - phone_redis
  phone_redis:
    image: redis:latest
    container_name: phone_redis
  phone_mariadb:
    image: mariadb:latest
    container_name: phone_mariadb
    environment:
      MARIADB_USER: user1
      MARIADB_PASSWORD: user1
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_parser
    volumes:
      - ./mariadb_parser_data:/var/lib/mysql
  phone_rabbit:
    image: rabbitmq:3-management
    container_name: phone_rabbit
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ./rabbit_data:/var/lib/rabbitmq
