name: Docker Image CI
on:
  push:
    branches: [ "main" ]
    paths:
      - front/**
jobs:
  build-and-push-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd front && docker build . --file Dockerfile --tag upachko/phone_front:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DHCL }}
        password: ${{ secrets.DCHP }}
    - name: Push To Docker Hub
      run: docker push -a upachko/phone_front
